-- CREATE SEARCH FUNCTIONS
-- Run this script to create the SQL-based search alternatives

-- First, verify the knowledge base table exists
SELECT 'Checking knowledge base table...' as STATUS;
SELECT COUNT(*) as DOCUMENT_COUNT FROM SNOWFLAKE_PUBSEC_DEMO.INTELLIGENCE.GOVERNMENT_KNOWLEDGE_BASE;

-- Create the advanced document search function
CREATE OR REPLACE FUNCTION SNOWFLAKE_PUBSEC_DEMO.INTELLIGENCE.ADVANCED_DOCUMENT_SEARCH(
    SEARCH_QUERY STRING
)
RETURNS TABLE (
    DOCUMENT_ID STRING,
    TITLE STRING,
    CONTENT_SNIPPET TEXT,
    AGENCY STRING,
    DOCUMENT_TYPE STRING,
    CLASSIFICATION STRING,
    RELEVANCE_SCORE NUMBER,
    MATCH_DETAILS STRING
)
LANGUAGE SQL
AS
$$
    WITH SEARCH_RESULTS AS (
        SELECT 
            DOCUMENT_ID,
            TITLE,
            CASE 
                WHEN UPPER(CONTENT) LIKE UPPER('%' || SEARCH_QUERY || '%') THEN
                    SUBSTR(CONTENT, 
                           GREATEST(1, POSITION(UPPER(SEARCH_QUERY) IN UPPER(CONTENT)) - 100), 
                           300) || '...'
                ELSE LEFT(CONTENT, 200) || '...'
            END as CONTENT_SNIPPET,
            AGENCY,
            DOCUMENT_TYPE,
            CLASSIFICATION,
            (
                CASE WHEN UPPER(TITLE) LIKE UPPER('%' || SEARCH_QUERY || '%') THEN 20 ELSE 0 END +
                CASE WHEN UPPER(CONTENT) LIKE UPPER('%' || SEARCH_QUERY || '%') THEN 15 ELSE 0 END +
                CASE WHEN UPPER(AGENCY) LIKE UPPER('%' || SEARCH_QUERY || '%') THEN 10 ELSE 0 END +
                CASE WHEN UPPER(DOCUMENT_TYPE) LIKE UPPER('%' || SEARCH_QUERY || '%') THEN 8 ELSE 0 END
            ) as RELEVANCE_SCORE,
            CONCAT(
                CASE WHEN UPPER(TITLE) LIKE UPPER('%' || SEARCH_QUERY || '%') THEN 'Title Match; ' ELSE '' END,
                CASE WHEN UPPER(CONTENT) LIKE UPPER('%' || SEARCH_QUERY || '%') THEN 'Content Match; ' ELSE '' END,
                CASE WHEN UPPER(AGENCY) LIKE UPPER('%' || SEARCH_QUERY || '%') THEN 'Agency Match; ' ELSE '' END
            ) as MATCH_DETAILS
        FROM SNOWFLAKE_PUBSEC_DEMO.INTELLIGENCE.GOVERNMENT_KNOWLEDGE_BASE
        WHERE 
            UPPER(TITLE) LIKE UPPER('%' || SEARCH_QUERY || '%') OR
            UPPER(CONTENT) LIKE UPPER('%' || SEARCH_QUERY || '%') OR
            UPPER(AGENCY) LIKE UPPER('%' || SEARCH_QUERY || '%') OR
            UPPER(DOCUMENT_TYPE) LIKE UPPER('%' || SEARCH_QUERY || '%')
    )
    SELECT * FROM SEARCH_RESULTS
    WHERE RELEVANCE_SCORE > 0
    ORDER BY RELEVANCE_SCORE DESC, TITLE
$$;

-- Create the multi-keyword search function
CREATE OR REPLACE FUNCTION SNOWFLAKE_PUBSEC_DEMO.INTELLIGENCE.MULTI_KEYWORD_SEARCH(
    KEYWORDS STRING
)
RETURNS TABLE (
    DOCUMENT_ID STRING,
    TITLE STRING,
    CONTENT_PREVIEW TEXT,
    AGENCY STRING,
    TOTAL_MATCHES NUMBER,
    KEYWORD_MATCHES STRING
)
LANGUAGE SQL
AS
$$
    WITH KEYWORD_SPLIT AS (
        SELECT 
            TRIM(SPLIT_PART(KEYWORDS, ' ', 1)) as KEYWORD1,
            TRIM(SPLIT_PART(KEYWORDS, ' ', 2)) as KEYWORD2,
            TRIM(SPLIT_PART(KEYWORDS, ' ', 3)) as KEYWORD3
    ),
    DOCUMENT_MATCHES AS (
        SELECT 
            kb.DOCUMENT_ID,
            kb.TITLE,
            LEFT(kb.CONTENT, 250) || '...' as CONTENT_PREVIEW,
            kb.AGENCY,
            (
                CASE WHEN ks.KEYWORD1 != '' AND (UPPER(kb.TITLE) LIKE UPPER('%' || ks.KEYWORD1 || '%') OR UPPER(kb.CONTENT) LIKE UPPER('%' || ks.KEYWORD1 || '%')) THEN 1 ELSE 0 END +
                CASE WHEN ks.KEYWORD2 != '' AND (UPPER(kb.TITLE) LIKE UPPER('%' || ks.KEYWORD2 || '%') OR UPPER(kb.CONTENT) LIKE UPPER('%' || ks.KEYWORD2 || '%')) THEN 1 ELSE 0 END +
                CASE WHEN ks.KEYWORD3 != '' AND (UPPER(kb.TITLE) LIKE UPPER('%' || ks.KEYWORD3 || '%') OR UPPER(kb.CONTENT) LIKE UPPER('%' || ks.KEYWORD3 || '%')) THEN 1 ELSE 0 END
            ) as TOTAL_MATCHES,
            CONCAT(
                CASE WHEN ks.KEYWORD1 != '' AND (UPPER(kb.TITLE) LIKE UPPER('%' || ks.KEYWORD1 || '%') OR UPPER(kb.CONTENT) LIKE UPPER('%' || ks.KEYWORD1 || '%')) THEN ks.KEYWORD1 || '; ' ELSE '' END,
                CASE WHEN ks.KEYWORD2 != '' AND (UPPER(kb.TITLE) LIKE UPPER('%' || ks.KEYWORD2 || '%') OR UPPER(kb.CONTENT) LIKE UPPER('%' || ks.KEYWORD2 || '%')) THEN ks.KEYWORD2 || '; ' ELSE '' END,
                CASE WHEN ks.KEYWORD3 != '' AND (UPPER(kb.TITLE) LIKE UPPER('%' || ks.KEYWORD3 || '%') OR UPPER(kb.CONTENT) LIKE UPPER('%' || ks.KEYWORD3 || '%')) THEN ks.KEYWORD3 || '; ' ELSE '' END
            ) as KEYWORD_MATCHES
        FROM SNOWFLAKE_PUBSEC_DEMO.INTELLIGENCE.GOVERNMENT_KNOWLEDGE_BASE kb
        CROSS JOIN KEYWORD_SPLIT ks
    )
    SELECT * FROM DOCUMENT_MATCHES
    WHERE TOTAL_MATCHES > 0
    ORDER BY TOTAL_MATCHES DESC, TITLE
$$;

-- Verify the functions were created
SELECT 'Search functions created successfully!' as STATUS;

-- Test the functions
SELECT 'Testing ADVANCED_DOCUMENT_SEARCH...' as TEST_STATUS;
SELECT * FROM TABLE(SNOWFLAKE_PUBSEC_DEMO.INTELLIGENCE.ADVANCED_DOCUMENT_SEARCH('Smart Nation'));

SELECT 'Testing MULTI_KEYWORD_SEARCH...' as TEST_STATUS;
SELECT * FROM TABLE(SNOWFLAKE_PUBSEC_DEMO.INTELLIGENCE.MULTI_KEYWORD_SEARCH('digital services'));

SELECT 'All search functions are ready to use!' as FINAL_STATUS;
